### ISSUE TITLE
The game freeze in 100%

### ISSUE THREAD

**Issue by miguelf03kai** [amhsirak/quantum#12]
the game freeze in one red bar with 100%, and nothing happens.

Documentation says "To Try This Own Your Own
Clone the repository:

git clone https://github.com/karishmas6/quantum.git
Have Fun! 🦄"

**Comment by amhsirak** [comment]
@miguelf03kai Thank you for pointing this out. 
The game was freezing because the images and audio folders were missing.
I have added those folders now. The game should work fine! 😄
If you still face any issues, let me know

**Comment by miguelf03kai** [comment]
> @miguelf03kai Thank you for pointing this out.
> The game was freezing because the images and audio folders were missing.
> I have added those folders now. The game should work fine! 😄
> If you still face any issues, let me know

the game is pretty interesting i liked
