### ISSUE TITLE
Add Pause - Resume functionality

### ISSUE THREAD

**Issue by amhsirak** [amhsirak/quantum#14]
It would be super cool to add a pause/resume functionality to the game. I thought of implementing it myself, but anyway decided to ask for help.
**What is to be done?**
- Add a pause/resume button at the green circled area.
- If possible when paused show a menu with options like Resume (to resume the game) , Home (to open home), and Restart (to play again)
![2021-09-30_LI](https://user-images.githubusercontent.com/76456498/135503353-60d96a60-ba21-4d97-b0d2-8c5fbc0a2ea2.jpg)

**Comment by karishmashuklaa** [comment]
I guess I will look into it myself lol

**Comment by amhsirak** [comment]
Closing cause I am not pursuing this at the moment
